[package]
name = "veil"
edition = "2024.beta"
license = "MIT"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }
# Confidential Transfers (Devnet public beta) - uncomment for W1
# contra = { git = "https://github.com/MystenLabs/confidential-transfers.git", subdir = "move", rev = "main" }

[addresses]
veil = "0x0"
